// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://besdtjhbciefgnokaasa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlc2R0amhiY2llZmdub2thYXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTY5NjMsImV4cCI6MjA2MDczMjk2M30.DutwrIF7cqFqG5JBBDNYOxDP-WT72-5ca5PonBzpHAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});